/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 21 13:49:44 GMT 2024
 */

package sg.edu.nus.comp.cs4218.impl.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PushbackInputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.app.TeeApplication;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TeeApplication_ESTest extends TeeApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      byte[] byteArray0 = new byte[4];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(byteArrayInputStream0, (byte)92);
      Boolean boolean0 = Boolean.valueOf(false);
      String string0 = teeApplication0.teeFromStdin(boolean0, pushbackInputStream0, stringArray0);
      assertEquals("tee: : Is a directory\r\n\u0000\u0000\u0000\u0000\r\n", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      Boolean boolean0 = Boolean.valueOf("sg.edu.nus.comp.cs4218.impl.app.TeeApplication");
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      String[] stringArray0 = new String[6];
      stringArray0[0] = "sg.edu.nus.comp.cs4218.impl.app.TeeApplication";
      try { 
        teeApplication0.teeFromStdin(boolean0, byteArrayInputStream0, stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: No such file or directory
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.helper.TeeApplicationHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      Enumeration<ByteArrayInputStream> enumeration0 = (Enumeration<ByteArrayInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      String[] stringArray0 = new String[0];
      String string0 = teeApplication0.teeFromStdin((Boolean) null, sequenceInputStream0, stringArray0);
      assertEquals("\r\n", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      Boolean boolean0 = Boolean.valueOf(false);
      InputStream inputStream0 = InputStream.nullInputStream();
      try { 
        teeApplication0.teeFromStdin(boolean0, inputStream0, (String[]) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: Null arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.TeeApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      Boolean boolean0 = Boolean.valueOf((String) null);
      String[] stringArray0 = new String[2];
      try { 
        teeApplication0.teeFromStdin(boolean0, (InputStream) null, stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: Null Pointer Exception
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.TeeApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      File file0 = MockFile.createTempFile("..W|*|&=4d|F0vV{x&", "..W|*|&=4d|F0vV{x&");
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(file0);
      String[] stringArray0 = new String[6];
      try { 
        teeApplication0.run(stringArray0, mockFileInputStream0, (OutputStream) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: OutputStream not provided
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.TeeApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      String[] stringArray0 = new String[2];
      MockFile mockFile0 = new MockFile("L 80&lOES*,OL6lsS");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, false);
      try { 
        teeApplication0.run(stringArray0, (InputStream) null, mockFileOutputStream0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: InputStream not provided
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.TeeApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      MockFile mockFile0 = new MockFile("..");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, false);
      try { 
        teeApplication0.run((String[]) null, (InputStream) null, mockFileOutputStream0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // tee: Insufficient arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.TeeApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TeeApplication teeApplication0 = new TeeApplication();
      String[] stringArray0 = new String[2];
      InputStream inputStream0 = InputStream.nullInputStream();
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      // Undeclared exception!
      try { 
        teeApplication0.run(stringArray0, inputStream0, outputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.parser.ArgsParser", e);
      }
  }
}
