name: Maven Tests Report

on:
  push:
    branches: ['main']
    tags: ['ms1', 'ms2', 'ms3']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Verify
        run: mvn --batch-mode --update-snapshots verify

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Test Report (${{ matrix.os }})
          path: target/surefire-reports/*Test.xml
          reporter: java-junit
          fail-on-error: true

      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Test Report (${{ matrix.os }})
          path: target/surefire-reports/*IT.xml
          reporter: java-junit
          fail-on-error: true