name: Maven Test Reports

on:
  push:
    branches: ['main']
    tags: ['ms1', 'ms2', 'ms3']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Unit Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Report
          path: target/surefire-reports/*Test.xml
          reporter: java-junit
          fail-on-error: true
        continue-on-error: true

      - name: Integration Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Test Report
          path: target/surefire-reports/*IT.xml
          reporter: java-junit
          fail-on-error: true
        continue-on-error: true

      - name: System Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: System Test Report
          path: target/surefire-reports/*SystemTest.xml
          reporter: java-junit
          fail-on-error: true
        continue-on-error: true
