name: PMD

on:
  push:
    branches: ['main']
    tags: ['ms1', 'ms2', 'ms3']
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          version: '6.55.0'
          rulesets: 'PMD.Rules.xml'